Fix : Resource Leak
alexander-naumov/pam2control pull request #11
Opened 2020-06-15 23:14 UTC by FollowMeDown

ok ?

2020-06-15 23:29 UTC, FollowMeDown commented
Proof of Make :
```
deface@proton ~/_/p/src (master)> make
gcc    -c -o pam2control.o pam2control.c
gcc    -c -o config.o config.c
gcc    -c -o log.o log.c
gcc    -c -o smtp.o smtp.c
gcc    -c -o conv.o conv.c
gcc -Wall -fPIC -c pam2control.c config.c log.c smtp.c conv.c
gcc -shared -o pam2control.so pam2control.o config.o log.o smtp.o conv.o -lpam
```

2020-06-15 23:53 UTC, FollowMeDown commented
If va_end is not called before returning from the function, the result is undefined.

2020-06-16 09:36 UTC, alexander-naumov requested changes
Well, we use `log_path` in log.c to define PATH of logfile.
You can't just change this name here; `logpath` will be NULL in `history()` func.

2020-06-16 09:37 UTC, alexander-naumov approved these changes
nice

2020-06-16 09:38 UTC, alexander-naumov reviewed
ok

2020-06-16 09:39 UTC, alexander-naumov reviewed
ok, thanks

2020-06-16 09:53 UTC, alexander-naumov requested changes

2020-06-16 09:53 UTC, alexander-naumov commented on src/config.c
> +    log_path_conf = def->LOGFILE;
Well, we use `log_path` in log.c to define PATH of logfile.
You can't just change this name here; `logpath` will be NULL in `history()` func.

2020-06-16 12:00 UTC, closed without merging